#ifndef __COLINUX_COMPAT_DDK_NDIS_H__
#define __COLINUX_COMPAT_DDK_NDIS_H__

#include <ddk/ntddk.h>

#ifndef NDIS_STATUS
typedef int NDIS_STATUS, *PNDIS_STATUS;
#endif

#ifndef UINT
typedef unsigned int UINT, *PUINT;
#endif

#ifndef NDIS_OID
typedef ULONG NDIS_OID, *PNDIS_OID;
#endif

#ifndef NDIS_OBJECT_HEADER
typedef struct _NDIS_OBJECT_HEADER {
  UCHAR Type;
  UCHAR Revision;
  USHORT Size;
} NDIS_OBJECT_HEADER, *PNDIS_OBJECT_HEADER;
#endif

#ifndef _NDIS_MEDIUM
typedef enum _NDIS_MEDIUM {
  NdisMedium802_3,
  NdisMedium802_5,
  NdisMediumFddi,
  NdisMediumWan,
  NdisMediumLocalTalk,
  NdisMediumDix,
  NdisMediumArcnetRaw,
  NdisMediumArcnet878_2,
  NdisMediumAtm,
  NdisMediumWirelessWan,
  NdisMediumIrda,
  NdisMediumBpc,
  NdisMediumCoWan,
  NdisMedium1394,
  NdisMediumInfiniBand,
#if NTDDI_VERSION >= 0x06000000
  NdisMediumTunnel,
  NdisMediumNative802_11,
  NdisMediumLoopback,
#endif
#if NTDDI_VERSION >= 0x06010000
  NdisMediumWiMAX,
  NdisMediumIP,
#endif
  NdisMediumMax
} NDIS_MEDIUM, *PNDIS_MEDIUM;
#endif

#ifndef _NDIS_WAN_QUALITY
typedef enum _NDIS_WAN_QUALITY {
  NdisWanRaw,
  NdisWanErrorControl,
  NdisWanReliable
} NDIS_WAN_QUALITY, *PNDIS_WAN_QUALITY;
#endif

#include "ndis_fixed.h"

#ifndef OID_802_3_PERMANENT_ADDRESS
#define OID_802_3_PERMANENT_ADDRESS 0x01010101
#endif
#ifndef OID_802_3_CURRENT_ADDRESS
#define OID_802_3_CURRENT_ADDRESS 0x01010102
#endif
#ifndef OID_802_3_MULTICAST_LIST
#define OID_802_3_MULTICAST_LIST 0x01010103
#endif
#ifndef OID_802_3_MAXIMUM_LIST_SIZE
#define OID_802_3_MAXIMUM_LIST_SIZE 0x01010104
#endif
#ifndef OID_802_3_XMIT_ONE_COLLISION
#define OID_802_3_XMIT_ONE_COLLISION 0x01020102
#endif
#ifndef OID_802_3_XMIT_MORE_COLLISIONS
#define OID_802_3_XMIT_MORE_COLLISIONS 0x01020103
#endif
#ifndef OID_802_3_RCV_ERROR_ALIGNMENT
#define OID_802_3_RCV_ERROR_ALIGNMENT 0x01020101
#endif

#ifndef OID_GEN_SUPPORTED_LIST
#define OID_GEN_SUPPORTED_LIST 0x00010101
#endif
#ifndef OID_GEN_HARDWARE_STATUS
#define OID_GEN_HARDWARE_STATUS 0x00010102
#endif
#ifndef OID_GEN_MEDIA_SUPPORTED
#define OID_GEN_MEDIA_SUPPORTED 0x00010103
#endif
#ifndef OID_GEN_MEDIA_IN_USE
#define OID_GEN_MEDIA_IN_USE 0x00010104
#endif
#ifndef OID_GEN_MAXIMUM_LOOKAHEAD
#define OID_GEN_MAXIMUM_LOOKAHEAD 0x00010105
#endif
#ifndef OID_GEN_MAXIMUM_FRAME_SIZE
#define OID_GEN_MAXIMUM_FRAME_SIZE 0x00010106
#endif
#ifndef OID_GEN_LINK_SPEED
#define OID_GEN_LINK_SPEED 0x00010107
#endif
#ifndef OID_GEN_TRANSMIT_BUFFER_SPACE
#define OID_GEN_TRANSMIT_BUFFER_SPACE 0x00010108
#endif
#ifndef OID_GEN_RECEIVE_BUFFER_SPACE
#define OID_GEN_RECEIVE_BUFFER_SPACE 0x00010109
#endif
#ifndef OID_GEN_TRANSMIT_BLOCK_SIZE
#define OID_GEN_TRANSMIT_BLOCK_SIZE 0x0001010a
#endif
#ifndef OID_GEN_RECEIVE_BLOCK_SIZE
#define OID_GEN_RECEIVE_BLOCK_SIZE 0x0001010b
#endif
#ifndef OID_GEN_VENDOR_ID
#define OID_GEN_VENDOR_ID 0x0001010c
#endif
#ifndef OID_GEN_VENDOR_DESCRIPTION
#define OID_GEN_VENDOR_DESCRIPTION 0x0001010d
#endif
#ifndef OID_GEN_CURRENT_PACKET_FILTER
#define OID_GEN_CURRENT_PACKET_FILTER 0x0001010e
#endif
#ifndef OID_GEN_CURRENT_LOOKAHEAD
#define OID_GEN_CURRENT_LOOKAHEAD 0x0001010f
#endif
#ifndef OID_GEN_DRIVER_VERSION
#define OID_GEN_DRIVER_VERSION 0x00010110
#endif
#ifndef OID_GEN_MAXIMUM_TOTAL_SIZE
#define OID_GEN_MAXIMUM_TOTAL_SIZE 0x00010111
#endif
#ifndef OID_GEN_PROTOCOL_OPTIONS
#define OID_GEN_PROTOCOL_OPTIONS 0x00010112
#endif
#ifndef OID_GEN_MAC_OPTIONS
#define OID_GEN_MAC_OPTIONS 0x00010113
#endif
#ifndef OID_GEN_MEDIA_CONNECT_STATUS
#define OID_GEN_MEDIA_CONNECT_STATUS 0x00010114
#endif
#ifndef OID_GEN_MAXIMUM_SEND_PACKETS
#define OID_GEN_MAXIMUM_SEND_PACKETS 0x00010115
#endif
#ifndef OID_GEN_VENDOR_DRIVER_VERSION
#define OID_GEN_VENDOR_DRIVER_VERSION 0x00010116
#endif
#ifndef OID_GEN_SUPPORTED_GUIDS
#define OID_GEN_SUPPORTED_GUIDS 0x00010117
#endif
#ifndef OID_GEN_NETWORK_LAYER_ADDRESSES
#define OID_GEN_NETWORK_LAYER_ADDRESSES 0x00010118
#endif
#ifndef OID_GEN_TRANSPORT_HEADER_OFFSET
#define OID_GEN_TRANSPORT_HEADER_OFFSET 0x00010119
#endif
#ifndef OID_GEN_MEDIA_CAPABILITIES
#define OID_GEN_MEDIA_CAPABILITIES 0x00010201
#endif
#ifndef OID_GEN_PHYSICAL_MEDIUM
#define OID_GEN_PHYSICAL_MEDIUM 0x00010202
#endif
#ifndef OID_GEN_RCV_OK
#define OID_GEN_RCV_OK 0x00020102
#endif
#ifndef OID_GEN_RCV_ERROR
#define OID_GEN_RCV_ERROR 0x00020104
#endif
#ifndef OID_GEN_RCV_NO_BUFFER
#define OID_GEN_RCV_NO_BUFFER 0x00020105
#endif
#ifndef OID_GEN_XMIT_OK
#define OID_GEN_XMIT_OK 0x00020101
#endif
#ifndef OID_GEN_XMIT_ERROR
#define OID_GEN_XMIT_ERROR 0x00020103
#endif
#ifndef OID_GEN_XMIT_LINK_SPEED
#define OID_GEN_XMIT_LINK_SPEED 0x00010284
#endif
#ifndef OID_GEN_DIRECTED_BYTES_XMIT
#define OID_GEN_DIRECTED_BYTES_XMIT 0x00020201
#endif
#ifndef OID_GEN_DIRECTED_FRAMES_XMIT
#define OID_GEN_DIRECTED_FRAMES_XMIT 0x00020202
#endif
#ifndef OID_GEN_MULTICAST_BYTES_XMIT
#define OID_GEN_MULTICAST_BYTES_XMIT 0x00020203
#endif
#ifndef OID_GEN_MULTICAST_FRAMES_XMIT
#define OID_GEN_MULTICAST_FRAMES_XMIT 0x00020204
#endif
#ifndef OID_GEN_BROADCAST_BYTES_XMIT
#define OID_GEN_BROADCAST_BYTES_XMIT 0x00020205
#endif
#ifndef OID_GEN_BROADCAST_FRAMES_XMIT
#define OID_GEN_BROADCAST_FRAMES_XMIT 0x00020206
#endif
#ifndef OID_GEN_DIRECTED_BYTES_RCV
#define OID_GEN_DIRECTED_BYTES_RCV 0x00020207
#endif
#ifndef OID_GEN_DIRECTED_FRAMES_RCV
#define OID_GEN_DIRECTED_FRAMES_RCV 0x00020208
#endif
#ifndef OID_GEN_MULTICAST_BYTES_RCV
#define OID_GEN_MULTICAST_BYTES_RCV 0x00020209
#endif
#ifndef OID_GEN_MULTICAST_FRAMES_RCV
#define OID_GEN_MULTICAST_FRAMES_RCV 0x0002020a
#endif
#ifndef OID_GEN_BROADCAST_BYTES_RCV
#define OID_GEN_BROADCAST_BYTES_RCV 0x0002020b
#endif
#ifndef OID_GEN_BROADCAST_FRAMES_RCV
#define OID_GEN_BROADCAST_FRAMES_RCV 0x0002020c
#endif
#ifndef OID_PNP_CAPABILITIES
#define OID_PNP_CAPABILITIES 0xfd010100
#endif
#ifndef OID_PNP_SET_POWER
#define OID_PNP_SET_POWER 0xfd010101
#endif
#ifndef OID_PNP_QUERY_POWER
#define OID_PNP_QUERY_POWER 0xfd010102
#endif
#ifndef OID_PNP_ADD_WAKE_UP_PATTERN
#define OID_PNP_ADD_WAKE_UP_PATTERN 0xfd010103
#endif
#ifndef OID_PNP_REMOVE_WAKE_UP_PATTERN
#define OID_PNP_REMOVE_WAKE_UP_PATTERN 0xfd010104
#endif
#ifndef OID_FFP_SUPPORT
#define OID_FFP_SUPPORT 0xfc010210
#endif
#ifndef OID_TCP_TASK_OFFLOAD
#define OID_TCP_TASK_OFFLOAD 0xfc010201
#endif

#endif
